blueprint:
  name: Lutron Pico Paddle
  description: "This is for the 2 button paddle picos that have the following model:\n\n
    PJ2-1P-GXX (PaddleSwitchPico)\n\nSelect an action for each button listed
    below. "
  domain: automation
  source_url: https://raw.githubusercontent.com/brandonschlack/blueprints/refs/heads/main/automation/lutron-caseta-pico-paddle.yaml
  homeassistant:
    min_version: '2024.6.0'
  input:
    pico_remote:
      name: Pico Remote
      description: 'Select the pico remote to configure:'
      selector:
        device:
          model: PJ2-3BRL-GXX-X01 (Pico3ButtonRaiseLower)
          multiple: false
    auto_mode:
      name: Automation Mode
      description: Mode that automation runs in (single,  restart, queued, parallel).
      default: restart
      selector:
        select:
          options:
          - single
          - restart
          - queued
          - parallel
          multiple: false
          custom_value: false
    mode_max:
      name: Mode Max (ignored by Single and Restart Modes)
      description: Maximum number of runs that can be executed or queued at a time.
      default: 10
      selector:
        number:
          min: 1.0
          max: 15.0
          mode: slider
          step: 1.0
    top_on:
      name: Top (On) Button Pressed
      description: Execute when TOP button is PRESSED
      default: []
      selector:
        action: {}
    top_on_release:
      name: Top (On) Button Released
      description: Execute when TOP button is RELEASED
      default: []
      selector:
        action: {}
    bottom_off:
      name: Bottom (Off) Button Pressed
      description: Execute when BOTTOM button is PRESSED
      default: []
      selector:
        action: {}
    bottom_off_release:
      name: Bottom (Off) Button Released
      description: Execute when BOTTOM button is RELEASED
      default: []
      selector:
        action: {}

mode: !input auto_mode
max: !input mode_max

triggers:
  - trigger: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'on'
    id: 'press_on'
  - trigger: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: press
    subtype: 'off'
    id: 'press_off'
  - trigger: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'on'
    id: 'release_on'
  - trigger: device
    device_id: !input pico_remote
    domain: lutron_caseta
    type: release
    subtype: 'off'
    id: 'release_off'

actions:
  - choose:
    - conditions: '{{ trigger.event.data.action == "press" }}'
      sequence:
        - choose:
          - conditions: '{{ trigger.event.data.button_number == 2 }}'
            sequence: !input top_on
          - conditions: '{{ trigger.event.data.button_number == 4 }}'
            sequence: !input bottom_off
    - conditions: '{{ trigger.event.data.action == "release" }}'
      sequence:
        - choose:
          - conditions: '{{ trigger.event.data.button_number == 2 }}'
            sequence: !input top_on_release
          - conditions: '{{ trigger.event.data.button_number == 4 }}'
            sequence: !input bottom_off_release
    default: []
